name: yalla_now_delivery
description: A new Flutter application.
publish_to: "none" #
version: 1.0.0+2

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.0.6
  connectivity_plus: ^5.0.2
  firebase_core: ^2.4.1
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.2.1+2
  path_provider: ^2.0.10
  url_strategy: ^0.2.0
  pin_code_fields: ^8.0.1
  http: ^1.2.1
  flutter_switch: ^0.3.2
  shimmer_animation: 2.0.0
  geolocator: ^10.1.0
  geocoding: ^2.0.0
  google_maps_flutter: ^2.0.6
  url_launcher: ^6.1.2
  image_picker: ^1.0.7
  disable_battery_optimization: ^1.1.0+1
  phone_numbers_parser: ^8.1.0
  country_code_picker: ^3.0.0
  audioplayers: ^5.2.1
  flutter_html: ^3.0.0-alpha.5
  cached_network_image: ^3.3.0
  flutter_image_compress: ^2.3.0
  win32: ^5.2.0
  path: ^1.8.1
  http_parser: ^4.0.2
  intl: ^0.19.0
  dotted_border: ^2.0.0+1
  photo_view: ^0.14.0
  web_socket_channel: ^2.4.0
  flutter_inappwebview: ^6.0.0
  just_the_tooltip: ^0.0.12
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: "^0.13.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

dependency_overrides:
  sky_engine:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#137ecd"
  adaptive_icon_foreground_inset: 10
  adaptive_icon_foreground: "assets/icon/logo.png"
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icon/
    - assets/svg/
    - assets/language/
    - assets/notification.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
